language: cpp
sudo: false
cache: ccache
notifications:
  slack:
    secure: AcgQWkBC+e09QyqJtC/hdPIt5w3Z29PM2tfmA37+H5dG22AlQRZTERoPD9Yj4RYfppqhY4MlAIs5E8LQvfS26hm+qHTAwDAZGQimI8Q8wVHPOsycFTzVVUme/J71pXaIdt5zzV0+9U/q1eNIJl3V92tRElsBTRTVC5591TpYkIeiDvNCnUf3arYNWdKz6GUIOYqTs7k922Lkq/zTZtfm+wlGS6s8ly8684yBR8rJ76xoJBsRPEVhkukcFOdm9Syn5Ad4L9yktJXOGc1O4hRfjp8oMwcMB9dwMgfwEOOC5KXsj/t0VD14SQLsOQ4CbVbofcVhUZnGu/hBpNTXAynfqYGUUHK/GaAkaC9Ih0Gn808rDZEX3siE7F5zLkfu/cv4t3jh6FR3Uy890IcnAZDLvOir6gotNS8b02TI6WxabvuhlyzM6YrGbijvCdl9clEy/dn49WPplm2YwsrAakZ+XA+/vFjfo6sE1IqQxK0M7A3TYK1bZ6o3dSrEG7ibSpiLrLKLkDzmUwRA56hLEGDjH01F71pAkP345gSzz7JNoGUgvheE2XAdkgMF/SYSwsmnRsfZhPCpQqjE9B0Sg/N3HPnpRUm84wex11cGyhKzEYlGOu3gG/MzgcyOhaFdDuRwbVOjULri1b5SegKO+Im8HpGpLhsYYFSo0NfwY49i+n4=
compiler:
- gcc
env:
  matrix:
  - COMPILER=g++-4.8 CCOMPILER=gcc-4.8 PUSH_COVERAGE=ON
  - COMPILER=g++-4.9 CCOMPILER=gcc-4.9
  - COMPILER=g++-5 CCOMPILER=gcc-5
  - COMPILER=clang++-3.6 CCOMPILER=clang-3.6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-precise
    - llvm-toolchain-precise-3.6
    packages:
    - g++-4.8
    - g++-4.9
    - g++-5
    - clang-3.6
    - libboost-all-dev
    - python-pip
install:
- if [ "$PUSH_COVERAGE" == "ON" ]; then pip install --user git+git://github.com/eddyxu/cpp-coveralls.git;
  fi
before_script:
- export CXX=$COMPILER CC=$CCOMPILER
- mkdir build
- cd build
- cmake --version
- cmake ..
script: make -j2 && ctest -j2
after_success:
- cd ..
- if [ "$PUSH_COVERAGE" == "ON" ]; then coveralls --gcov gcov-4.8 -i include --gcov-options
  '\-lp'; fi
